// This file is generated by Astro DB
declare module 'astro:db' {
	export const Products: import("@astrojs/db/runtime").Table<
		"Products",
		{"name":{"type":"text","schema":{"unique":false,"deprecated":false,"name":"name","collection":"Products","primaryKey":true}},"description":{"type":"text","schema":{"unique":false,"deprecated":false,"name":"description","collection":"Products","primaryKey":false,"optional":false}},"icon":{"type":"text","schema":{"unique":false,"deprecated":false,"name":"icon","collection":"Products","primaryKey":false,"optional":false}}}
	>;
}
